package cli

import (
	"github.com/spf13/cobra"
)

// rootCmd represents the base command when called without any subcommands.
// It serves as the entry point for the Superviz CLI application, which is a
// declarative process supervisor tool. The command is configured with the
// "svz" name and includes basic configuration to disable auto-generated tags
// and flags in the usage line for cleaner help output.
var rootCmd = &cobra.Command{
	Use:                   "svz",
	Short:                 "Superviz - Declarative Process Supervisor",
	DisableAutoGenTag:     true, // Removes "Auto generated by spf13/cobra"
	DisableFlagsInUseLine: true, // Cleaner usage line without [flags]
}

// GetCLICommand returns the root cobra command for the CLI application.
// This function provides access to the main command structure that serves as
// the entry point for all CLI operations.
//
// Parameters:
//   - None
//
// Returns:
//   - *cobra.Command: The root command instance that contains all subcommands
//
// GetCLICommand returns the root Cobra command for the Superviz CLI application.
func GetCLICommand() *cobra.Command {
	return rootCmd
}

// init registers all subcommands with the root command.
// init registers the version subcommand with the root CLI command when the package is initialized.
func init() {
	// Register the version subcommand
	rootCmd.AddCommand(GetVersionCommand())
}
