package cli

import (
	"github.com/spf13/cobra"
)

// rootCmd represents the base command when called without any subcommands.
//
// It serves as the entry point for the Superviz CLI application,
// a declarative process supervisor tool. This command is configured
// with the name "svz" and disables Cobra's autogenerated tags and
// flags in the usage line to produce a cleaner help output.
var rootCmd = &cobra.Command{
	Use:                   "svz",
	Short:                 "Superviz - Declarative Process Supervisor",
	DisableAutoGenTag:     true,
	DisableFlagsInUseLine: true,
}

// GetCLICommand returns the root Cobra command for the Superviz CLI application.
//
// This function exposes the base command instance, which serves as the
// entry point for all subcommands and operations within the CLI.
//
// Returns:
//
//   - *cobra.Command: The root Cobra command of the CLI.
func GetCLICommand() *cobra.Command {
	return rootCmd
}

// init registers all CLI subcommands with the root command.
//
// This function is automatically invoked at package initialization.
// It currently attaches the "version" subcommand to the root.
func init() {
	rootCmd.AddCommand(GetVersionCommand())
}
