name: CI

on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: write
  packages: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  analyze:
    name: Analyze + Versioning
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.semver.outputs.next }}
      current: ${{ steps.semver.outputs.current }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: What is next version?
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main
          skipInvalidTags: true
          noVersionBumpBehavior: patch
          noNewCommitBehavior: current
          patchList: "vendor, update, fix, bugfix, perf, refactor, test, tests, chore, ci, docs, improve, style, build, revert, improvement, enhancement, coverage, clean"

      - name: Install gotestsum
        run: |
          go install gotest.tools/gotestsum@latest
          echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"
      
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          only-new-issues: true

      - name: Run all the tests and code checks
        run: make test

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build:
    name: Build CLI Snapshot
    runs-on: ubuntu-latest
    needs: [analyze]
    outputs:
      version: ${{ steps.meta.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x

      - name: Set build metadata
        id: meta
        run: |
          COMMIT=$(git rev-parse --short HEAD)
          DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ)
          BUILT_BY="ci"
          VERSION="${{ needs.analyze.outputs.version }}-dev+${COMMIT}"
          GOVERSION=$(go version | awk '{print $3}')

          echo "version=$VERSION"     >> "$GITHUB_OUTPUT"
          echo "commit=$COMMIT"       >> "$GITHUB_OUTPUT"
          echo "date=$DATE"           >> "$GITHUB_OUTPUT"
          echo "builtBy=$BUILT_BY"    >> "$GITHUB_OUTPUT"
          echo "goVersion=$GOVERSION" >> "$GITHUB_OUTPUT"

      - name: Build with GoReleaser (snapshot)
        uses: goreleaser/goreleaser-action@v6
        with:
          args: build --snapshot --clean
        env:
          GORELEASER_CURRENT_TAG: ${{ steps.meta.outputs.version }}
          VERSION: ${{ steps.meta.outputs.version }}
          COMMIT: ${{ steps.meta.outputs.commit }}
          DATE: ${{ steps.meta.outputs.date }}
          BUILT_BY: ${{ steps.meta.outputs.builtBy }}
          GOVERSION: ${{ steps.meta.outputs.goVersion }}

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: svz-binaries
          path: .dist/
          if-no-files-found: error
          include-hidden-files: true

  release:
    name: Tag + Publish
    if: github.ref == 'refs/heads/main'
    needs: [analyze, build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ needs.analyze.outputs.version }}
          git push origin ${{ needs.analyze.outputs.version }}

      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          name: svz-binaries
          path: .dist/

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          name: Superviz.io ${{ needs.analyze.outputs.version }}
          tag: ${{ needs.analyze.outputs.version }}
          artifacts: .dist/bin/**
          makeLatest: true
          allowUpdates: true
          skipIfReleaseExists: true
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
