name: CI

on:
  push:
    branches: [main]
    tags: ['*']
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  packages: write

jobs:
  analyze:
    name: Analyze + Versioning
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.semver.outputs.next }}
      current: ${{ steps.semver.outputs.current }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: What is next version?
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main
          skipInvalidTags: true
          noVersionBumpBehavior: patch
          noNewCommitBehavior: current
          patchList: 'vendor, update, fix, bugfix, perf, refactor, test, tests, chore, ci, docs, improve, style, build, revert, improvement, enhancement, coverage, clean'

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build:
    name: Build CLI Snapshot
    runs-on: ubuntu-latest
    needs: analyze
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x

      - name: Set build metadata
        id: meta
        run: |
          COMMIT=$(git rev-parse --short HEAD)
          DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ)
          BUILT_BY="ci"
          VERSION="${{ needs.analyze.outputs.version }}-dev+${COMMIT}"

          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "commit=$COMMIT" >> "$GITHUB_OUTPUT"
          echo "date=$DATE" >> "$GITHUB_OUTPUT"
          echo "builtBy=$BUILT_BY" >> "$GITHUB_OUTPUT"

      - name: Build with GoReleaser (snapshot)
        uses: goreleaser/goreleaser-action@v6
        with:
          args: build --snapshot --clean
        env:
          GORELEASER_CURRENT_TAG: ${{ steps.meta.outputs.version }}
          VERSION: ${{ steps.meta.outputs.version }}
          COMMIT: ${{ steps.meta.outputs.commit }}
          DATE: ${{ steps.meta.outputs.date }}
          BUILT_BY: ${{ steps.meta.outputs.builtBy }}

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: svz-binaries
          path: dist/